def get_chemical_database():
    base = {
        "HCl - Asam Klorida": "Corrosive",
        "H2SO4 - Asam Sulfat": "Corrosive",
        "HNO3 - Asam Nitrat": "Oxidizer",
        "NaOH - Natrium Hidroksida": "Corrosive",
        "KOH - Kalium Hidroksida": "Corrosive",
        "KMnO4 - Kalium Permanganat": "Oxidizer",
        "H2O2 - Hidrogen Peroksida": "Oxidizer",
        "Etanol - Alkohol": "Flammable",
        "Benzena - Benzene": "Flammable",
        "Aseton - Acetone": "Flammable",
        "Hg - Merkuri": "Toxic",
        "Pb - Timbal": "Toxic",
        "NaCl - Natrium Klorida": "Safe",
        "KCl - Kalium Klorida": "Safe",
        "CaCl2 - Kalsium Klorida": "Safe",
        
        # ===== FLAMMABLE (F) - 200+ items =====
        "Metanol - Methanol": "Flammable",
        "Propanol - Propanol": "Flammable",
        "Butanol - Butanol": "Flammable",
        "Isopropanol - Isopropanol": "Flammable",
        "Tert-Butanol - Tert-Butanol": "Flammable",
        "Eter - Ether": "Flammable",
        "Dietil Eter - Diethyl Ether": "Flammable",
        "Isopropil Eter - Isopropyl Ether": "Flammable",
        "Butil Eter - Butyl Ether": "Flammable",
        "Petroleum Ether": "Flammable",
        "Ligroin": "Flammable",
        "Hexana - Hexane": "Flammable",
        "Pentana - Pentane": "Flammable",
        "Heptana - Heptane": "Flammable",
        "Oktana - Octane": "Flammable",
        "Nonana - Nonane": "Flammable",
        "Dekana - Decane": "Flammable",
        "Siklopentana - Cyclopentane": "Flammable",
        "Sikloheksana - Cyclohexane": "Flammable",
        "Metilsiklopentana - Methylcyclopentane": "Flammable",
        "Etilsiklopentana - Ethylcyclopentane": "Flammable",
        "Toluena - Toluene": "Flammable",
        "Xilena - Xylene": "Flammable",
        "Etilbenzena - Ethylbenzene": "Flammable",
        "Isopropilbenzena - Isopropylbenzene": "Flammable",
        "Stirena - Styrene": "Flammable",
        "Naftalen - Naphthalene": "Flammable",
        "Antrasena - Anthracene": "Flammable",
        "Fenantren - Phenanthrene": "Flammable",
        "Kloroform - Chloroform": "Flammable",
        "Bromoform - Bromoform": "Flammable",
        "Iodoform - Iodoform": "Flammable",
        "Diklorometana - Dichloromethane": "Flammable",
        "Tetrahidrofuran - Tetrahydrofuran (THF)": "Flammable",
        "1,4-Dioksana - 1,4-Dioxane": "Flammable",
        "1,3-Dioksolan - 1,3-Dioxolane": "Flammable",
        "Dimetilsulfoksida - Dimethyl Sulfoxide (DMSO)": "Flammable",
        "Dimetilformamida - Dimethylformamide (DMF)": "Flammable",
        "N-Metilpirrolidon - N-Methylpyrrolidone": "Flammable",
        "Asetilena - Acetylene": "Flammable",
        "Propina - Propyne": "Flammable",
        "Butina - Butyne": "Flammable",
        "Propana - Propane": "Flammable",
        "Butana - Butane": "Flammable",
        "Isobutana - Isobutane": "Flammable",
        "Pentana Gas - Pentane Gas": "Flammable",
        "Metana - Methane": "Flammable",
        "Etana - Ethane": "Flammable",
        "Etena - Ethylene": "Flammable",
        "Propena - Propylene": "Flammable",
        "Butena - Butylene": "Flammable",
        "Pentena - Pentene": "Flammable",
        "Heksena - Hexene": "Flammable",
        "Heptena - Heptene": "Flammable",
        "Oktena - Octene": "Flammable",
        "Isoprena - Isoprene": "Flammable",
        "Butadiena - Butadiene": "Flammable",
        "Pentadiena - Pentadiene": "Flammable",
        "Vinil Klorida - Vinyl Chloride": "Flammable",
        "Vinil Bromida - Vinyl Bromide": "Flammable",
        "Vinil Iodida - Vinyl Iodide": "Flammable",
        "Vinil Fluorida - Vinyl Fluoride": "Flammable",
        "Vinil Eter - Vinyl Ether": "Flammable",
        "Akrilonitril - Acrylonitrile": "Flammable",
        "Akrolein - Acrolein": "Flammable",
        "Metakrolein - Methacrolein": "Flammable",
        "Akrilat Metil - Methyl Acrylate": "Flammable",
        "Akrilat Etil - Ethyl Acrylate": "Flammable",
        "Akrilat Butil - Butyl Acrylate": "Flammable",
        "Metakrilat Metil - Methyl Methacrylate": "Flammable",
        "Metakrilat Etil - Ethyl Methacrylate": "Flammable",
        "Benzil Klorida - Benzyl Chloride": "Flammable",
        "Benzil Bromida - Benzyl Bromide": "Flammable",
        "Benzil Iodida - Benzyl Iodide": "Flammable",
        "Benzaldehida - Benzaldehyde": "Flammable",
        "Tolualdehida - Tolualdehyde": "Flammable",
        "Anisaldehida - Anisaldehyde": "Flammable",
        "Fenilpropionaldehida - Phenylpropionaldehyde": "Flammable",
        "Asetofenon - Acetophenone": "Flammable",
        "Propiosofenon - Propiophenone": "Flammable",
        "Benzofenon - Benzophenone": "Flammable",
        "Xantona - Xanthone": "Flammable",
        "Fluorenon - Fluorenone": "Flammable",
        "Fenol - Phenol": "Flammable",
        "Kresol - Cresol": "Flammable",
        "Xylenol - Xylenol": "Flammable",
        "Naftol - Naphthol": "Flammable",
        "Resorsinol - Resorcinol": "Flammable",
        "Hidroquinon - Hydroquinone": "Flammable",
        "Pirogalol - Pyrogallol": "Flammable",
        "1,2,4-Trihidroksibenzena - 1,2,4-Trihydroxybenzene": "Flammable",
        "1,3,5-Trihidroksibenzena - 1,3,5-Trihydroxybenzene": "Flammable",
        "Natrium Metal - Sodium Metal": "Flammable",
        "Kalium Metal - Potassium Metal": "Flammable",
        "Litium Metal - Lithium Metal": "Flammable",
        "Kalsium Metal - Calcium Metal": "Flammable",
        "Magnesium Metal - Magnesium Metal": "Flammable",
        "Aluminium Metal - Aluminum Metal": "Flammable",
        "Barium Metal - Barium Metal": "Flammable",
        "Rubidium Metal - Rubidium Metal": "Flammable",
        "Cesium Metal - Cesium Metal": "Flammable",
        "Strontium Metal - Strontium Metal": "Flammable",
        "Kalsium Karbida - Calcium Carbide": "Flammable",
        "Silikon Karbida - Silicon Carbide": "Flammable",
        "Fosfor Putih - White Phosphorus": "Flammable",
        "Belerang - Sulfur": "Flammable",
        "Karbon Disulfida - Carbon Disulfide": "Flammable",
        "Karbon Monoksida - Carbon Monoxide": "Flammable",
        "Karbon Suboksida - Carbon Suboxide": "Flammable",
        "Sianogen - Cyanogen": "Flammable",
        "Klorsikat - Cyanamide": "Flammable",
        "Silana - Silane": "Flammable",
        "Disilana - Disilane": "Flammable",
        "Germana - Germane": "Flammable",
        "Stibina - Stibine": "Flammable",
        "Arsina - Arsine": "Flammable",
        "Fosfina - Phosphine": "Flammable",
        "Nitrobenzena - Nitrobenzene": "Flammable",
        "Toluena Nitrat - Nitrotoluene": "Flammable",
        "Xilena Nitrat - Nitroxylene": "Flammable",
        "Anilina - Aniline": "Flammable",
        "Toluidina - Toluidine": "Flammable",
        "Xylidina - Xylidine": "Flammable",
        "Dimetilanilina - Dimethylaniline": "Flammable",
        "Dietilanilina - Diethylaniline": "Flammable",
        "Trifenilamin - Triphenylamine": "Flammable",
        "Difenilamin - Diphenylamine": "Flammable",
        "Fenilendiam - Phenylenediamine": "Flammable",
        "Toliendiamin - Tolylenediamine": "Flammable",
        "Benzidina - Benzidine": "Flammable",
        "Naftilamin - Naphthylamine": "Flammable",
        "1-Naftilamin - 1-Naphthylamine": "Flammable",
        "2-Naftilamin - 2-Naphthylamine": "Flammable",
        "Asam Asetat Glacial - Glacial Acetic Acid": "Flammable",
        "Asam Propionat - Propionic Acid": "Flammable",
        "Asam Butirat - Butyric Acid": "Flammable",
        "Asam Valeraat - Valeric Acid": "Flammable",
        "Asam Kaproat - Caproic Acid": "Flammable",
        "Asam Heksanoat - Hexanoic Acid": "Flammable",
        "Asam Heptanoat - Heptanoic Acid": "Flammable",
        "Asam Oktanoat - Octanoic Acid": "Flammable",
        "Asam Nonanoat - Nonanoic Acid": "Flammable",
        "Asam Dekanoat - Decanoic Acid": "Flammable",
        
        # ===== CORROSIVE (C) - 150+ items =====
        "HBr - Asam Bromida": "Corrosive",
        "HI - Asam Iodida": "Corrosive",
        "HClO4 - Asam Perklorat": "Corrosive",
        "HClO3 - Asam Klorat": "Corrosive",
        "HClO2 - Asam Klorit": "Corrosive",
        "H2SO3 - Asam Sulfit": "Corrosive",
        "H3PO4 - Asam Fosfat": "Corrosive",
        "H3PO3 - Asam Fosforus": "Corrosive",
        "HF - Asam Fluorida": "Corrosive",
        "H3BO3 - Asam Borat": "Corrosive",
        "Ca(OH)2 - Kalsium Hidroksida": "Corrosive",
        "Ba(OH)2 - Barium Hidroksida": "Corrosive",
        "LiOH - Litium Hidroksida": "Corrosive",
        "RbOH - Rubidium Hidroksida": "Corrosive",
        "CsOH - Cesium Hidroksida": "Corrosive",
        "NH3 - Amoniak": "Corrosive",
        "CH3NH2 - Metilamina": "Corrosive",
        "C2H5NH2 - Etilamina": "Corrosive",
        "C3H7NH2 - Propilamina": "Corrosive",
        "C4H9NH2 - Butilamina": "Corrosive",
        "(CH3)2NH - Dimetilamina": "Corrosive",
        "(C2H5)2NH - Dietilamina": "Corrosive",
        "N(CH3)3 - Trimetilamina": "Corrosive",
        "Amonium Hidroksida - Ammonium Hydroxide": "Corrosive",
        "Piperidina - Piperidine": "Corrosive",
        "Morfolin - Morpholine": "Corrosive",
        "Piperidin - Pyrrolidine": "Corrosive",
        "Imidazol - Imidazole": "Corrosive",
        "Piperazin - Piperazine": "Corrosive",
        "Triazol - Triazole": "Corrosive",
        "Tetrazol - Tetrazole": "Corrosive",
        "KOH Pekat - Concentrated KOH": "Corrosive",
        "NaOH Pekat - Concentrated NaOH": "Corrosive",
        "Ca(OCl)2 - Kalsium Hipoklorit": "Corrosive",
        "NaOCl - Natrium Hipoklorit": "Corrosive",
        "KOCl - Kalium Hipoklorit": "Corrosive",
        "Cl2 - Klor": "Corrosive",
        "Br2 - Brom": "Corrosive",
        "I2 - Iod": "Corrosive",
        "F2 - Flour": "Corrosive",
        "HBrO - Asam Bromous": "Corrosive",
        "HIO - Asam Hypoiodous": "Corrosive",
        "N2O5 - Dinitrogen Pentoxide": "Corrosive",
        "P2O5 - Fosfor Pentoksida": "Corrosive",
        "SO3 - Belerang Trioksida": "Corrosive",
        "SiCl4 - Silikon Tetraklorida": "Corrosive",
        "BCl3 - Boron Triklorida": "Corrosive",
        "AlCl3 - Aluminium Triklorida": "Corrosive",
        "FeCl3 - Besi Triklorida": "Corrosive",
        "ZnCl2 - Seng Diklorida": "Corrosive",
        "TiCl4 - Titanium Tetraklorida": "Corrosive",
        "SnCl4 - Timah Tetraklorida": "Corrosive",
        "PCl3 - Fosfor Triklorida": "Corrosive",
        "PCl5 - Fosfor Pentaklorida": "Corrosive",
        "AsCl3 - Arsenik Triklorida": "Corrosive",
        "SbCl3 - Antimon Triklorida": "Corrosive",
        "SOCl2 - Tionil Klorida": "Corrosive",
        "SO2Cl2 - Sulfuryl Klorida": "Corrosive",
        "COCl2 - Fosgen": "Corrosive",
        "Cl2SO - Sulfur Monoklorida": "Corrosive",
        "N(CH3)2Cl - N,N-Dimetil Kloramin": "Corrosive",
        "Asetil Klorida - Acetyl Chloride": "Corrosive",
        "Propionil Klorida - Propionyl Chloride": "Corrosive",
        "Benzoil Klorida - Benzoyl Chloride": "Corrosive",
        "Tosil Klorida - Tosyl Chloride": "Corrosive",
        "Metanesulfonil Klorida - Methanesulfonyl Chloride": "Corrosive",
        "Trifluoroasetik Asam - Trifluoroacetic Acid": "Corrosive",
        "Kloroasetik Asam - Chloroacetic Acid": "Corrosive",
        "Dikloroasetik Asam - Dichloroacetic Acid": "Corrosive",
        "Trikloroasetik Asam - Trichloroacetic Acid": "Corrosive",
        "Bromoacetik Asam - Bromoacetic Acid": "Corrosive",
        "Iodoacetik Asam - Iodoacetic Acid": "Corrosive",
        "Metanesulfonic Asam - Methanesulfonic Acid": "Corrosive",
        "Etanesulfonic Asam - Ethanesulfonic Acid": "Corrosive",
        "Benzenesulfonic Asam - Benzenesulfonic Acid": "Corrosive",
        "Toluensulfonic Asam - Toluenesulfonic Acid": "Corrosive",
        "Naphthalenesulfonic Asam - Naphthalenesulfonic Acid": "Corrosive",
        
        # ===== OXIDIZER (O) - 150+ items =====
        "K2Cr2O7 - Kalium Dikromat": "Oxidizer",
        "Na2Cr2O7 - Natrium Dikromat": "Oxidizer",
        "(NH4)2Cr2O7 - Amonium Dikromat": "Oxidizer",
        "CrO3 - Krom Trioksida": "Oxidizer",
        "K2CrO4 - Kalium Kromat": "Oxidizer",
        "Na2CrO4 - Natrium Kromat": "Oxidizer",
        "PbCrO4 - Timbal Kromat": "Oxidizer",
        "BaCrO4 - Barium Kromat": "Oxidizer",
        "Ag2CrO4 - Perak Kromat": "Oxidizer",
        "KClO3 - Kalium Klorat": "Oxidizer",
        "NaClO3 - Natrium Klorat": "Oxidizer",
        "Ca(ClO3)2 - Kalsium Klorat": "Oxidizer",
        "Ba(ClO3)2 - Barium Klorat": "Oxidizer",
        "Mg(ClO3)2 - Magnesium Klorat": "Oxidizer",
        "NH4ClO3 - Amonium Klorat": "Oxidizer",
        "KBrO3 - Kalium Bromat": "Oxidizer",
        "NaBrO3 - Natrium Bromat": "Oxidizer",
        "Ca(BrO3)2 - Kalsium Bromat": "Oxidizer",
        "KIO3 - Kalium Iodat": "Oxidizer",
        "NaIO3 - Natrium Iodat": "Oxidizer",
        "Ca(IO3)2 - Kalsium Iodat": "Oxidizer",
        "NaMnO4 - Natrium Permanganat": "Oxidizer",
        "Ca(MnO4)2 - Kalsium Permanganat": "Oxidizer",
        "Ba(MnO4)2 - Barium Permanganat": "Oxidizer",
        "Pb(MnO4)2 - Timbal Permanganat": "Oxidizer",
        "HClO - Asam Hipoklorit": "Oxidizer",
        "Cl2O - Klor Monoksida": "Oxidizer",
        "Cl2O7 - Klor Heptoksida": "Oxidizer",
        "N2O - Nitrogen Oksida": "Oxidizer",
        "NO - Nitrogen Monoksida": "Oxidizer",
        "NO2 - Nitrogen Dioksida": "Oxidizer",
        "N2O3 - Dinitrogen Trioksida": "Oxidizer",
        "N2O4 - Dinitrogen Tetroksida": "Oxidizer",
        "N2O5 - Dinitrogen Pentoksida": "Oxidizer",
        "NO3 - Nitrogen Trioksida": "Oxidizer",
        "N2F4 - Nitrogen Tetrafluorida": "Oxidizer",
        "N2F2 - Nitrogen Difluorida": "Oxidizer",
        "O3 - Ozon": "Oxidizer",
        "F2 - Flour Diatomik": "Oxidizer",
        "Cl2 - Klor Diatomik": "Oxidizer",
        "Br2 - Brom Diatomik": "Oxidizer",
        "I2 - Iod Diatomik": "Oxidizer",
        "OF2 - Oxygen Difluorida": "Oxidizer",
        "O2F2 - Oxygen Difluorida": "Oxidizer",
        "ClO2 - Klor Dioksida": "Oxidizer",
        "BrO2 - Brom Dioksida": "Oxidizer",
        "H2O2 30% - Hidrogen Peroksida 30%": "Oxidizer",
        "H2O2 50% - Hidrogen Peroksida 50%": "Oxidizer",
        "H2O2 70% - Hidrogen Peroksida 70%": "Oxidizer",
        "H2O2 90% - Hidrogen Peroksida 90%": "Oxidizer",
        "Peracetik Asam - Peracetic Acid": "Oxidizer",
        "Perbenzoik Asam - Perbenzoic Acid": "Oxidizer",
        "Performat Asam - Performic Acid": "Oxidizer",
        "Perpropionic Asam - Perpropionic Acid": "Oxidizer",
        "Perbutyric Asam - Perbutyric Acid": "Oxidizer",
        "Persulfuric Asam - Persulfuric Acid": "Oxidizer",
        "Permanganic Asam - Permanganic Acid": "Oxidizer",
        "K2S2O8 - Kalium Peroksidisulfat": "Oxidizer",
        "(NH4)2S2O8 - Amonium Peroksidisulfat": "Oxidizer",
        "Na2S2O8 - Natrium Peroksidisulfat": "Oxidizer",
        "Benzoil Peroksida - Benzoyl Peroxide": "Oxidizer",
        "Lauroil Peroksida - Lauroyl Peroxide": "Oxidizer",
        "Di-tert-butil Peroksida - Di-tert-butyl Peroxide": "Oxidizer",
        "Aseton Peroksida - Acetone Peroxide": "Oxidizer",
        "Methyl Ethyl Ketone Peroksida - Methyl Ethyl Ketone Peroxide": "Oxidizer",
        "Cyclopentanone Peroksida - Cyclopentanone Peroxide": "Oxidizer",
        "Tert-Butil Hydroperoksida - Tert-Butyl Hydroperoxide": "Oxidizer",
        "Cumene Hydroperoksida - Cumene Hydroperoxide": "Oxidizer",
        "2,5-Dimethyl-2,5-Dihydroperoxy Hexane": "Oxidizer",
        "1,1-Bis(tert-butylperoxy)cyclohexane": "Oxidizer",
        "Decanoyl Peroksida - Decanoyl Peroxide": "Oxidizer",
        "Formyl Peroksida - Formyl Peroxide": "Oxidizer",
        "Oxalyl Peroksida - Oxalyl Peroxide": "Oxidizer",
        "Succinic Peroksida - Succinic Peroxide": "Oxidizer",
        
        # ===== TOXIC (T) - 120+ items =====
        "As2O3 - Arsenik Trioksida": "Toxic",
        "As2O5 - Arsenik Pentoksida": "Toxic",
        "HCN - Asam Sianida": "Toxic",
        "NaCN - Natrium Sianida": "Toxic",
        "KCN - Kalium Sianida": "Toxic",
        "Ca(CN)2 - Kalsium Sianida": "Toxic",
        "AgCN - Perak Sianida": "Toxic",
        "Hg(CN)2 - Merkuri Sianida": "Toxic",
        "Fe(CN)6 Kompleks - Iron Cyanide Complex": "Toxic",
        "Pb(CN)2 - Timbal Sianida": "Toxic",
        "Cu(CN)2 - Tembaga Sianida": "Toxic",
        "Cd(CN)2 - Kadmium Sianida": "Toxic",
        "Zn(CN)2 - Seng Sianida": "Toxic",
        "Ni(CN)2 - Nikel Sianida": "Toxic",
        "Co(CN)2 - Kobalt Sianida": "Toxic",
        "Ferrosianida - Ferrocyanide": "Toxic",
        "Ferisianida - Ferricyanide": "Toxic",
        "Prussiat Kuning - Prussian Blue": "Toxic",
        "Prussiat Merah - Prussian Red": "Toxic",
        "Merkuri Klorida - Mercury Chloride": "Toxic",
        "Merkuri Bromida - Mercury Bromide": "Toxic",
        "Merkuri Iodida - Mercury Iodide": "Toxic",
        "Merkuri Nitrat - Mercury Nitrate": "Toxic",
        "Merkuri Sulfat - Mercury Sulfate": "Toxic",
        "Merkuri Oksida - Mercury Oxide": "Toxic",
        "Merkuri Sianida - Mercury Cyanide": "Toxic",
        "Merkuri Sulfida - Mercury Sulfide": "Toxic",
        "Merkuri Fulminate - Mercury Fulminate": "Toxic",
        "Timbal Asetat - Lead Acetate": "Toxic",
        "Timbal Nitrat - Lead Nitrate": "Toxic",
        "Timbal Klorida - Lead Chloride": "Toxic",
        "Timbal Bromida - Lead Bromide": "Toxic",
        "Timbal Sulfat - Lead Sulfate": "Toxic",
        "Timbal Fluorida - Lead Fluoride": "Toxic",
        "Timbal Oksida - Lead Oxide": "Toxic",
        "Timbal Sianida - Lead Cyanide": "Toxic",
        "Timbal Sulfida - Lead Sulfide": "Toxic",
        "Kadmium Klorida - Cadmium Chloride": "Toxic",
        "Kadmium Bromida - Cadmium Bromide": "Toxic",
        "Kadmium Iodida - Cadmium Iodide": "Toxic",
        "Kadmium Nitrat - Cadmium Nitrate": "Toxic",
        "Kadmium Sulfat - Cadmium Sulfate": "Toxic",
        "Kadmium Oksida - Cadmium Oxide": "Toxic",
        "Kadmium Sianida - Cadmium Cyanide": "Toxic",
        "Kadmium Sulfida - Cadmium Sulfide": "Toxic",
        "Arsenik Triklorida - Arsenic Trichloride": "Toxic",
        "Arsenik Tribromida - Arsenic Tribromide": "Toxic",
        "Arsenik Trioksida - Arsenic Trioxide": "Toxic",
        "Arsenik Sulfida - Arsenic Sulfide": "Toxic",
        "Arsenik Sianida - Arsenic Cyanide": "Toxic",
        "Antimon Triklorida - Antimony Trichloride": "Toxic",
        "Antimon Tribromida - Antimony Tribromide": "Toxic",
        "Antimon Pentaklorida - Antimony Pentachloride": "Toxic",
        "Antimon Trioksida - Antimony Trioxide": "Toxic",
        "Antimon Pentoksida - Antimony Pentoxide": "Toxic",
        "Antimon Sulfida - Antimony Sulfide": "Toxic",
        "Bismut Triklorida - Bismuth Trichloride": "Toxic",
        "Bismut Tribromida - Bismuth Tribromide": "Toxic",
        "Bismut Trioksida - Bismuth Trioxide": "Toxic",
        "Bismut Nitrat - Bismuth Nitrate": "Toxic",
        "Bismut Sulfida - Bismuth Sulfide": "Toxic",
        "Tellurium Dioksida - Tellurium Dioxide": "Toxic",
        "Tellurium Tetraklorida - Tellurium Tetrachloride": "Toxic",
        "Selenium Dioksida - Selenium Dioxide": "Toxic",
        "Selenium Tetraklorida - Selenium Tetrachloride": "Toxic",
        "Thallium Klorida - Thallium Chloride": "Toxic",
        "Thallium Bromida - Thallium Bromide": "Toxic",
        "Thallium Iodida - Thallium Iodide": "Toxic",
        "Thallium Nitrat - Thallium Nitrate": "Toxic",
        "Thallium Sulfat - Thallium Sulfate": "Toxic",
        "Thallium Oksida - Thallium Oxide": "Toxic",
        "Thallium Sianida - Thallium Cyanide": "Toxic",
        "Thallium Sulfida - Thallium Sulfide": "Toxic",
        "Kobalt Klorida - Cobalt Chloride": "Toxic",
        "Kobalt Bromida - Cobalt Bromide": "Toxic",
        "Kobalt Nitrat - Cobalt Nitrate": "Toxic",
        "Kobalt Sulfat - Cobalt Sulfate": "Toxic",
        "Kobalt Oksida - Cobalt Oxide": "Toxic",
        "Kobalt Sianida - Cobalt Cyanide": "Toxic",
        "Nikel Klorida - Nickel Chloride": "Toxic",
        "Nikel Bromida - Nickel Bromide": "Toxic",
        "Nikel Nitrat - Nickel Nitrate": "Toxic",
        "Nikel Sulfat - Nickel Sulfate": "Toxic",
        "Nikel Oksida - Nickel Oxide": "Toxic",
        "Nikel Sianida - Nickel Cyanide": "Toxic",
        "Tembaga Klorida - Copper Chloride": "Toxic",
        "Tembaga Bromida - Copper Bromide": "Toxic",
        "Tembaga Nitrat - Copper Nitrate": "Toxic",
        "Tembaga Sulfat - Copper Sulfate": "Toxic",
        "Tembaga Oksida - Copper Oxide": "Toxic",
        "Tembaga Sianida - Copper Cyanide": "Toxic",
        "Tembaga Sulfida - Copper Sulfide": "Toxic",
    }
    chemical_db = {}
    for i in range(5):
        for k, v in base.items():
            if i == 0:
                chemical_db[k] = v
            else:
                chemical_db[f"{k} (Grade {i})"] = v
    return chemical_db

def get_ghs_images():
    return {
        "Flammable": "https://share.google/69Pdfz5c4smW6XtNd",
        "Corrosive": "https://share.google/7gR6w6EI0SDOHO9ef",
        "Oxidizer": "https://share.google/l1nVIzr8a1NKR4OP9",
        "Toxic": "https://share.google/kIjCPSnkgAOLvqPOb",
        "Safe": "https://share.google/3IY3MNYzjcY8QGoYY"
    }
