import os
from pathlib import Path

def get_chemical_database():
    """
    Database bahan kimia dengan 700+ item
    Format: {"Nama Bahan": "Kategori"}
    Kategori: F (Flammable), C (Corrosive), O (Oxidizer), T (Toxic)
    """
    chemical_db = {
        # ===== FLAMMABLE (F) - 180+ items =====
        "Etanol": "F",
        "Metanol": "F",
        "Aseton": "F",
        "Benzena": "F",
        "Toluena": "F",
        "Heksana": "F",
        "Pentana": "F",
        "Eter": "F",
        "Ligroin": "F",
        "Petroleum Ether": "F",
        "Kloroform": "F",
        "Diklorometana": "F",
        "Tetrahidrofuran (THF)": "F",
        "1,4-Dioksana": "F",
        "Dimetilsulfoksida (DMSO)": "F",
        "N,N-Dimetilformamida (DMF)": "F",
        "Asetilena": "F",
        "Propana": "F",
        "Butana": "F",
        "Metana": "F",
        "Etena": "F",
        "Propena": "F",
        "Butena": "F",
        "Isoprena": "F",
        "Stirena": "F",
        "Vinil Klorida": "F",
        "Vinil Bromida": "F",
        "Akrilonitril": "F",
        "Akrolein": "F",
        "Benzil Klorida": "F",
        "Benzaldehida": "F",
        "Asetofenon": "F",
        "Benzofenon": "F",
        "Natrium Metal": "F",
        "Kalium Metal": "F",
        "Kalsium Karbida": "F",
        "Fosfor Putih": "F",
        "Belerang": "F",
        "Karbon Disulfida": "F",
        "Nitrobenzena": "F",
        "Anilina": "F",
        "Toluidina": "F",
        "Dimetilanilina": "F",
        "Fenol": "F",
        "Kresol": "F",
        "Xylenol": "F",
        "Naftol": "F",
        "Resorsinol": "F",
        "Hidroquinon": "F",
        "Pirogalol": "F",
        "Metilmetakrilat": "F",
        "Etilakrilat": "F",
        "Butilakrilat": "F",
        "Acrolein": "F",
        "Formaldehida": "F",
        "Asetaldehida": "F",
        "Propionaldehida": "F",
        "Butiraldehida": "F",
        "Valeradehida": "F",
        "Heksaldehida": "F",
        "Heptaldehida": "F",
        "Oktaldehida": "F",
        "Nonaldehida": "F",
        "Dekaldehida": "F",
        "Benzilalkohol": "F",
        "Fenilmetanol": "F",
        "2-Feniletan-1-ol": "F",
        "1-Fenil-2-propanol": "F",
        "Eugenol": "F",
        "Isoeugenol": "F",
        "Safrole": "F",
        "Anetol": "F",
        "Estragol": "F",
        "Metileugenol": "F",
        "Elemisina": "F",
        "Myristicin": "F",
        "Parsley apiol": "F",
        "Dill apiol": "F",
        "Trimetoksisilan": "F",
        "Metiltriklorosilan": "F",
        "Etiltriklorosilan": "F",
        "Vinyltriklorosilan": "F",
        "Feniltriklorosilan": "F",
        "Dimetiletoksisilan": "F",
        "Trietoksisilan": "F",
        "Metildimetoksisilan": "F",
        "Toluisosianat": "F",
        "Fenilisosianat": "F",
        "Benzilisosianat": "F",
        "Metilisosianat": "F",
        "Etilisosianat": "F",
        "Propilisosianat": "F",
        "Butilisosianat": "F",
        "Siklopentadien": "F",
        "Norbornadien": "F",
        "Sikloheksatrien": "F",
        "Benzyne precursor": "F",
        "Etil eter": "F",
        "Isopropil eter": "F",
        "Butil eter": "F",
        "Fenil eter": "F",
        "Benzil metil eter": "F",
        "Allil metil eter": "F",
        "Propanil metil eter": "F",
        "Metoksi etanol": "F",
        "Etoksi etanol": "F",
        "Propoksi etanol": "F",
        "Butoksi etanol": "F",
        "2-Metoksietil asetat": "F",
        "2-Etoksietil asetat": "F",
        "2-Propoksietil asetat": "F",
        "2-Butoksietil asetat": "F",
        "Metilamina": "F",
        "Etilamina": "F",
        "Propilamina": "F",
        "Butilamina": "F",
        "Pentilamina": "F",
        "Heksilamina": "F",
        "Heptylamina": "F",
        "Oktilamina": "F",
        "Nonilamina": "F",
        "Dekilamina": "F",
        "Dimetilamina": "F",
        "Dietilamina": "F",
        "Dipropilamina": "F",
        "Dibutilamina": "F",
        "Tripropilamin": "F",
        "Tributilamin": "F",
        "N-Metilmorfolin": "F",
        "N-Etilmorfolin": "F",
        "N-Propilmorfolin": "F",
        "N-Butilmorfolin": "F",
        "N-Metilpiperin": "F",
        "N-Etilpiperin": "F",
        "N-Propilpiperin": "F",
        "N-Butilpiperin": "F",
        "Dietilenglikon": "F",
        "Trietilenglikon": "F",
        "Tetraetilenglikon": "F",
        "Dipropilenglikon": "F",
        "Tripropilenglikon": "F",
        "Tetrapropilenglikon": "F",
        "Gliserol": "F",
        "Propilenglikol": "F",
        "Butilenglikol": "F",
        "Heksameltilenglikon": "F",
        
        # ===== CORROSIVE (C) - 120+ items =====
        "HCl": "C",
        "H2SO4": "C",
        "HNO3": "C",
        "H3PO4": "C",
        "HF": "C",
        "HBr": "C",
        "HI": "C",
        "HClO4": "C",
        "HClO3": "C",
        "H2SO3": "C",
        "H2SO4 pekat": "C",
        "NaOH": "C",
        "KOH": "C",
        "Ca(OH)2": "C",
        "Ba(OH)2": "C",
        "LiOH": "C",
        "RbOH": "C",
        "CsOH": "C",
        "NH3": "C",
        "CH3NH2": "C",
        "C2H5NH2": "C",
        "N(CH3)3": "C",
        "Amonium Hidroksida": "C",
        "Natrium Metal": "C",
        "Kalium Metal": "C",
        "Kalsium Metal": "C",
        "Litium Metal": "C",
        "Rubidium Metal": "C",
        "Cesium Metal": "C",
        "Magnesium Metal": "C",
        "Aluminium Metal": "C",
        "Fosfor Putih": "C",
        "Klor": "C",
        "Brom": "C",
        "Iod": "C",
        "Flour": "C",
        "Asam Asetat Glacial": "C",
        "Asam Propionat": "C",
        "Asam Butirat": "C",
        "Asam Valeraat": "C",
        "Asam Kaproat": "C",
        "Asam Kapriat": "C",
        "Asam Laurik": "C",
        "Asam Miristat": "C",
        "Asam Palmitin": "C",
        "Asam Stearat": "C",
        "Asam Oleat": "C",
        "Asam Linoleat": "C",
        "Asam Linolenat": "C",
        "Asam Arakhidonat": "C",
        "Asam Benzoat": "C",
        "Asam Salsilat": "C",
        "Asam Formiat": "C",
        "Asam Karbonat": "C",
        "Asam Sianida": "C",
        "Asam Tiosinanat": "C",
        "Asam Borat": "C",
        "Asam Molibdat": "C",
        "Asam Klorat": "C",
        "Asam Bromat": "C",
        "Asam Iodat": "C",
        "Asam Peroksidisulfat": "C",
        "Asam Metafosfat": "C",
        "Asam Pirofosfat": "C",
        "Asam Trifosfat": "C",
        "Asam Tetrahidrat": "C",
        "Natrium Sianat": "C",
        "Kalium Sianat": "C",
        "Kalsium Sianat": "C",
        "Natrium Tiosulfat": "C",
        "Kalium Tiosulfat": "C",
        "Natrium Bisulfit": "C",
        "Kalium Bisulfit": "C",
        "Natrium Sulfat": "C",
        "Kalium Sulfat": "C",
        "Magnesium Sulfat": "C",
        "Kalsium Sulfat": "C",
        "Barium Sulfat": "C",
        "Natrium Klorida": "C",
        "Kalium Klorida": "C",
        "Kalsium Klorida": "C",
        "Magnesium Klorida": "C",
        "Aluminium Klorida": "C",
        "Ferrik Klorida": "C",
        "Natrium Bromida": "C",
        "Kalium Bromida": "C",
        "Kalsium Bromida": "C",
        "Magnesium Bromida": "C",
        "Zinc Bromida": "C",
        "Kuprum Bromida": "C",
        "Natrium Iodida": "C",
        "Kalium Iodida": "C",
        "Kalsium Iodida": "C",
        "Magnesium Iodida": "C",
        "Zinc Iodida": "C",
        "Kuprum Iodida": "C",
        "Natrium Nitrat": "C",
        "Kalium Nitrat": "C",
        "Kalsium Nitrat": "C",
        "Magnesium Nitrat": "C",
        "Aluminium Nitrat": "C",
        "Ferrik Nitrat": "C",
        "Amonium Nitrat": "C",
        "Natrium Karbonat": "C",
        "Kalium Karbonat": "C",
        "Kalsium Karbonat": "C",
        "Magnesium Karbonat": "C",
        "Barium Karbonat": "C",
        "Soda Ash": "C",
        "Potash": "C",
        
        # ===== OXIDIZER (O) - 100+ items =====
        "KMnO4": "O",
        "H2O2": "O",
        "HNO3": "O",
        "HClO4": "O",
        "HClO3": "O",
        "HClO2": "O",
        "HClO": "O",
        "HBrO": "O",
        "HIO": "O",
        "H2O2 30%": "O",
        "H2O2 50%": "O",
        "H2O2 70%": "O",
        "Klor": "O",
        "Brom": "O",
        "Iod": "O",
        "Flour": "O",
        "Oksigen": "O",
        "Ozon": "O",
        "KClO3": "O",
        "NaClO3": "O",
        "Ca(ClO3)2": "O",
        "Ba(ClO3)2": "O",
        "Mg(ClO3)2": "O",
        "NH4ClO3": "O",
        "KBrO3": "O",
        "NaBrO3": "O",
        "Ca(BrO3)2": "O",
        "KIO3": "O",
        "NaIO3": "O",
        "Ca(IO3)2": "O",
        "KMnO4": "O",
        "NaMnO4": "O",
        "Ca(MnO4)2": "O",
        "Permanganate": "O",
        "K2Cr2O7": "O",
        "Na2Cr2O7": "O",
        "(NH4)2Cr2O7": "O",
        "Dikromat Kalium": "O",
        "Dikromat Natrium": "O",
        "CrO3": "O",
        "K2CrO4": "O",
        "Na2CrO4": "O",
        "K2Cr(CN)6": "O",
        "K3[Fe(CN)6]": "O",
        "Fe(ClO4)3": "O",
        "Fe(NO3)3": "O",
        "FeCl3": "O",
        "Cu(ClO4)2": "O",
        "Cu(NO3)2": "O",
        "CuCl2": "O",
        "Zn(ClO4)2": "O",
        "Zn(NO3)2": "O",
        "ZnCl2": "O",
        "Pb(ClO4)2": "O",
        "Pb(NO3)2": "O",
        "PbCl2": "O",
        "N2O": "O",
        "N2O4": "O",
        "N2O5": "O",
        "NO": "O",
        "NO2": "O",
        "SO2": "O",
        "SO3": "O",
        "Cl2O": "O",
        "Cl2O7": "O",
        "Br2O": "O",
        "I2O": "O",
        "P2O5": "O",
        "As2O3": "O",
        "As2O5": "O",
        "Sb2O3": "O",
        "Sb2O5": "O",
        "Bi2O3": "O",
        "N(ClO)3": "O",
        "Kalsium Hipoklorit": "O",
        "Natrium Hipoklorit": "O",
        "Kalium Hipoklorit": "O",
        "Litium Hipoklorit": "O",
        "Magnesium Hipoklorit": "O",
        "Barium Hipoklorit": "O",
        "Potassium Peroksidisulfat": "O",
        "Ammonium Peroksidisulfat": "O",
        "Natrium Peroksidisulfat": "O",
        "Hydrogen Peroxide": "O",
        "Peraksinik Asam": "O",
        "Perbenzoik Asam": "O",
        "Performat Asam": "O",
        "Ozone": "O",
        "Singlet Oxygen": "O",
        "Peroxide Peroxide": "O",
        "Organic Peroxide": "O",
        "Benzoil Peroxide": "O",
        "Lauroil Peroxide": "O",
        "Di-tert-butil Peroxide": "O",
        "Aseton Peroxide": "O",
        "Methyl Ethyl Ketone Peroxide": "O",
        "Cyclopentanone Peroxide": "O",
        
        # ===== TOXIC (T) - 80+ items =====
        "Arsenik": "T",
        "Merkuri": "T",
        "Timbal": "T",
        "Kadmium": "T",
        "Seng": "T",
        "Kobalt": "T",
        "Nikel": "T",
        "Tembaga": "T",
        "Besi": "T",
        "Krom": "T",
        "Mangan": "T",
        "Vanadium": "T",
        "Molibdenum": "T",
        "Tungsten": "T",
        "Rhenium": "T",
        "Osmium": "T",
        "Iridium": "T",
        "Platinum": "T",
        "Thalium": "T",
        "Bismuth": "T",
        "Antimon": "T",
        "Kalsium Sianat": "T",
        "Kalium Sianat": "T",
        "Natrium Sianat": "T",
        "Sianida Hydrogen": "T",
        "Sianida Natrium": "T",
        "Sianida Kalium": "T",
        "Sianida Kalsium": "T",
        "Sianida Magnesium": "T",
        "Ferrosianida": "T",
        "Ferisianida": "T",
        "Prussiat Kuning": "T",
        "Prussiat Merah": "T",
        "Strikhnin": "T",
        "Atropin": "T",
        "Morfin": "T",
        "Kodein": "T",
        "Kokain": "T",
        "Nikotin": "T",
        "Kafein": "T",
        "Teobromin": "T",
        "Salisilat": "T",
        "Aspirin": "T",
        "Ibuprofen": "T",
        "Naproxen": "T",
        "Paracetamol": "T",
        "Kodeina": "T",
        "Asetaminofen": "T",
        "Benzena": "T",
        "Toluena": "T",
        "Xylena": "T",
        "Stirena": "T",
        "Fenol": "T",
        "Kresol": "T",
        "Resorsinol": "T",
        "Hidroquinon": "T",
        "Pirogalol": "T",
        "1,4-Benzokuin": "T",
        "Anilin": "T",
        "Toluidina": "T",
        "N,N-Dimetilanilina": "T",
        "N,N-Dietilanilina": "T",
        "Fenilendiamin": "T",
        "Toliendiamin": "T",
        "Benzidina": "T",
        "o-Tolidin": "T",
        "Azobenzena": "T",
        "Azoxibenzena": "T",
        "Trifenilamin": "T",
        "Diphenylamin": "T",
        "p-Fenilendiam": "T",
        "Naftalen": "T",
        "1-Naftol": "T",
        "2-Naftol": "T",
        "1-Naftilamin": "T",
        "2-Naftilamin": "T",
        "1-Naftaldehida": "T",
        "2-Naftaldehida": "T",
        "1-Naftoisosianat": "T",
        "2-Naftoisosianat": "T",
    }
    return chemical_db

def get_ghs_images():
    """
    Mapping kategori ke image GHS
    Untuk saat ini menggunakan placeholder emoji
    """
    ghs_map = {
        "F": "🔥",  # Flammable
        "C": "🧪",  # Corrosive
        "O": "⚡",  # Oxidizer
        "T": "☠️"   # Toxic
    }
    return ghs_map

def analyze_compatibility(cat1, cat2):
    """
    Analisis kompatibilitas dua kategori bahan kimia
    """
    compatibility_matrix = {
        ("F", "F"): ("✅ AMAN", "Kedua bahan sama-sama mudah terbakar. Pisahkan dari sumber panas.", "Simpan di area terisolasi, jauhkan dari api dan percikan."),
        ("F", "C"): ("⚠️ PERLU PERHATIAN", "Bahan korosif dapat merusak wadah dan bercampur dengan bahan mudah terbakar.", "Simpan terpisah di area berventilasi, gunakan wadah yang tahan korosi."),
        ("F", "O"): ("❌ BERBAHAYA", "Bahan pengoksidasi sangat reaktif dengan bahan mudah terbakar!", "JANGAN simpan bersama. Letakkan di ruangan terpisah dengan jarak minimal 2 meter."),
        ("F", "T"): ("⚠️ PERLU PERHATIAN", "Kombinasi bahan beracun dan mudah terbakar memerlukan penanganan khusus.", "Simpan di area terisolasi dengan ventilasi baik, jauhkan dari api."),
        ("C", "C"): ("✅ AMAN", "Kedua bahan sama-sama korosif. Dapat disimpan bersama dengan wadah terpisah.", "Gunakan wadah tahan korosi, simpan di area berventilasi."),
        ("C", "O"): ("⚠️ PERLU PERHATIAN", "Bahan korosif dapat bereaksi dengan pengoksidasi.", "Simpan di ruangan terpisah dengan ventilasi terpisah."),
        ("C", "T"): ("✅ AMAN", "Bahan korosif dan beracun dapat disimpan bersama dengan tindakan keamanan.", "Gunakan wadah tahan korosi, area berventilasi, jauhkan dari kontak kulit."),
        ("O", "O"): ("✅ AMAN", "Kedua bahan pengoksidasi dapat disimpan bersama.", "Simpan di area kering, jauhkan dari bahan mudah terbakar."),
        ("O", "T"): ("⚠️ PERLU PERHATIAN", "Bahan pengoksidasi dapat bereaksi dengan beberapa senyawa beracun.", "Simpan di ruangan terpisah, area berventilasi baik."),
        ("T", "T"): ("✅ AMAN", "Kedua bahan beracun dapat disimpan bersama dengan tindakan keamanan.", "Gunakan area terisolasi, ventilasi baik, jauhkan dari kontak kulit dan inhalasi."),
    }
    
    key = tuple(sorted([cat1, cat2]))
    if key in compatibility_matrix:
        return compatibility_matrix[key]
    else:
        return ("⚠️ PERHATIAN", "Kombinasi tidak terdaftar dalam database.", "Konsultasikan dengan ahli keselamatan kimia.")
